name: fern-check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-definitions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Fern
        run: npm install -g fern-api

      - name: Check API definition is valid
        run: fern check
