name: Upgrade Generators

on:
  schedule:
    # Run daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for branches
          token: ${{ secrets.SCHEMATIC_BOT_GH_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install Fern
        run: npm install -g fern-api

      - name: Install yq
        uses: mikefarah/yq@master

      - name: Upgrade generators
        env:
          GITHUB_TOKEN: ${{ secrets.SCHEMATIC_BOT_GH_TOKEN }}
        run: ./scripts/upgrade_generators.sh
